Refactor readme
go-siris/siris pull request #9
Opened 2017-06-24 13:05 UTC by godofdream

2017-06-24 13:40 UTC, Dexus submitted a review, later dismissed
At last we should use a "code of conduct" and a "contibution" markdown. To perform the GITHUB state of the art recommendations for contributions etc.

And at last good work!

2017-06-24 13:40 UTC, Dexus commented on LICENSE
> +Copyright (c) 2017 Go-siris team. All rights reserved.
Can you please change this to Go-SIRIS team?

2017-06-24 13:40 UTC, Dexus commented on README.md
> +| high performance | TODO add to [speedtest](https://github.com/smallnest/go-web-framework-benchmark) |
Is already done. Only a test run need to be done.

2017-06-24 13:40 UTC, Dexus commented on README.md
> +| Updates | Checks for Updates |
Looks like this is not implemented... or was never...

2017-06-24 13:44 UTC, Dexus commented
A example for the [contributing.md](https://github.com/blog/1184-contributing-guidelines) i like: https://github.com/haraka/Haraka/wiki/Contributing

2017-06-24 13:47 UTC, Dexus commented
Via https://github.com/go-siris/siris/community/code-of-conduct/new?template=contributor-covenant you can create a new code-of-conduct.md

2017-06-25 11:30 UTC, Dexus commented
Can you also create a contributing.md?

2017-06-25 16:59 UTC, Dexus requested changes

2017-06-25 16:59 UTC, Dexus commented on contributing.md
> +To submit new_branch as a Pull Request, visit the [Haraka project page](https://github.com/go-siris/siris) where your recently pushed branches will appear with a green "Pull Request" button.
SIRIS project page

2017-06-25 16:59 UTC, Dexus commented on contributing.md
> +We love and appreciate contributions to Go-Siris.
Go-SIRIS ;)

2017-06-25 17:07 UTC, Dexus commented
When done with the changes, it can be pushed to branch devel.
Better will be with two PR, where the vendor changes are splitted from the "refactor readme".

Regards, Dexus (Josef)

2017-06-25 17:18 UTC, godofdream commented on contributing.md
> +To submit new_branch as a Pull Request, visit the [Haraka project page](https://github.com/go-siris/siris) where your recently pushed branches will appear with a green "Pull Request" button.
aah damn XD

2017-06-25 17:54 UTC, godofdream commented
see https://github.com/go-siris/siris/pull/18

2017-06-25 17:54 UTC, closed without merging

2017-06-25 18:01 UTC, Dexus commented on contributing.md
> +git remote add haraka https://github.com/go-siris/siris.git
DAMN, `haraka` need to be `siris`?

2017-06-25 20:16 UTC, godofdream commented on contributing.md
> +git remote add haraka https://github.com/go-siris/siris.git
sorry i have overseen this one, i will fix it on devel

2017-06-25 20:28 UTC, godofdream commented on contributing.md
> +git remote add haraka https://github.com/go-siris/siris.git
fixed in https://github.com/go-siris/siris/commit/38b22d38ba9247a346f02c1cd53d046483f70500